### ISSUE TITLE
Trello::Error exception creating card

### ISSUE THREAD

**Issue by floehopper** [freerange/webhooks#2]
We've seen the following exception occur in production against [this version of the code](https://github.com/freerange/webhooks/blob/c12ad2531937483d74803f956a869108af531a29/app.rb):

    App 22493 stdout: 
    [ 2014-07-08 08:01:15.6772 2949/7f57ae239700 Pool2/SmartSpawner.h:297 ]: Preloader for /home/freerange/app started on PID 22493, listening on unix:/tmp/passenger.1.0.2943/generation-0/backends/preloader.22493
    App 22510 stdout: 
    App 21028 stderr: Trello::Error - Trello::Error:
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.0.4/lib/trello/client.rb:98:in `invoke_verb'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.0.4/lib/trello/client.rb:23:in `post'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.0.4/lib/trello/card.rb:79:in `save'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.0.4/lib/trello/basic_data.rb:25:in `save'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.0.4/lib/trello/client.rb:66:in `create'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.0.4/lib/trello/card.rb:20:in `create'
    App 21028 stderr:       /home/webhooks/app/app.rb:32:in `block in <top (required)>'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/logger.rb:15:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/
    App 21045 stdout: E, [2014-07-08T08:01:44.442930 #21045] ERROR -- : [ POST https://api.trello.com/1/cards]: 
    App 21028 stderr: ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
    App 21028 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
    App 21028 stderr:       /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
    App 21028 stderr:       /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
    App 21028 stderr:       /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
    App 21028 stderr:       /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'
    App 21028 stderr: 
    App 21028 stderr: 178.79.161.133 - - [08/Jul/2014 08:01:44] "POST /harmonia/assignments " 500 30 10.4153

**Comment by floehopper** [comment]
This happened so long ago and the code has changed significantly, so I'm not convinced it's worth investigating. Also I have a feeling the problem may have been a temporary one at the Trello end. Closing.
