### ISSUE TITLE
Exception ArgumentError in Rack application object (invalid %-encoding)

### ISSUE THREAD

**Issue by floehopper** [freerange/webhooks#21]
When [this Harmonia task][1] was first assigned, it looks as if the following exception occurred:

    App 17414 stderr: [ 2016-06-21 03:16:09.9431 17431/0x000000023bdfb0(Worker 1) utils.rb:84 ]: *** Exception ArgumentError in Rack application object (invalid %-encoding ({"assignment":{"key":"2bxnid","created_at":"2016-06-21T04:16:06.949+01:00","task":{"key":"6t467a","name":"3CA end of year adjustments 2014","instructions":"---------- Forwarded message ----------\r\nFrom: Team at Proactive \u003cteam@proactive.uk.net\u003e\r\nDate: 21 June 2016 at 03:46\r\nSubject: Re: 3CA end of year adjustments 2014\r\nTo: Go Free Range Ltd \u003ceveryone@gofreerange.com\u003e\r\n\r\n\r\nHi James\r\n\r\n\r\n\r\nThanks for your feedback on the phone on Friday and for letting me\r\nhave the summary page relating to the 3CA journal. It doesn’t shed\r\nmuch light on things, and simply confirms what we said verbally. The\r\nfigure of £1,518.10 is the resultant VAT from a more detailed\r\ncalculation which (based on your document “3CA end of year adjustments\r\n2014.pdf”) probably included:\r\n\r\n\r\n\r\nA bit of output VAT on extra sales of 50.65\r\nA bit of input VAT on extra expenses of 1212.02\r\n\r\n\r\n\r\nAnd because 20% of those amounts doesn’t help me . . .  –10.13 +\r\n242.40 )) (process 17431, thread 0x000000023bdfb0(Worker 1)):
    App 17414 stderr:       from /usr/lib/ruby/2.1.0/uri/common.rb:901:in `decode_www_form_component'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:42:in `unescape'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:105:in `block (2 levels) in parse_nested_query'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:105:in `map'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:105:in `block in parse_nested_query'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:104:in `each'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:104:in `parse_nested_query'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/request.rb:375:in `parse_query'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/request.rb:213:in `POST'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/methodoverride.rb:26:in `method_override'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/methodoverride.rb:14:in `call'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
    App 17414 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
    App 17414 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
    App 17414 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
    App 17414 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
    [Tue Jun 21 03:16:09.943673 2016] [core:error] [pid 10100:tid 140391105902336] [client 178.79.161.133:34930] End of script output before headers: harmonia

[1]: https://harmonia.io/teams/h54uvc/tasks/6t467a

**Comment by floehopper** [comment]
I've confirmed the above by re-assigning the task in Harmonia. I saw the following output in `/var/log/apache2/error.log`:

    App 17414 stderr: [ 2016-06-22 12:54:01.4158 17431/0x000000023bdfb0(Worker 1) utils.rb:84 ]: *** Exception ArgumentError in Rack application object (invalid %-encoding ({"assignment":{"key":"dsettu","created_at":"2016-06-22T13:53:59.938+01:00","task":{"key":"6t467a","name":"3CA end of year adjustments 2014","instructions":"---------- Forwarded message ----------\r\nFrom: Team at Proactive \u003cteam@proactive.uk.net\u003e\r\nDate: 21 June 2016 at 03:46\r\nSubject: Re: 3CA end of year adjustments 2014\r\nTo: Go Free Range Ltd \u003ceveryone@gofreerange.com\u003e\r\n\r\n\r\nHi James\r\n\r\n\r\n\r\nThanks for your feedback on the phone on Friday and for letting me\r\nhave the summary page relating to the 3CA journal. It doesn’t shed\r\nmuch light on things, and simply confirms what we said verbally. The\r\nfigure of £1,518.10 is the resultant VAT from a more detailed\r\ncalculation which (based on your document “3CA end of year adjustments\r\n2014.pdf”) probably included:\r\n\r\n\r\n\r\nA bit of output VAT on extra sales of 50.65\r\nA bit of input VAT on extra expenses of 1212.02\r\n\r\n\r\n\r\nAnd because 20% of those amounts doesn’t help me . . .  –10.13 +\r\n242.40 )) (process 17431, thread 0x000000023bdfb0(Worker 1)):
    App 17414 stderr:       from /usr/lib/ruby/2.1.0/uri/common.rb:901:in `decode_www_form_component'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:42:in `unescape'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:105:in `block (2 levels) in parse_nested_query'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:105:in `map'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:105:in `block in parse_nested_query'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:104:in `each'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/utils.rb:104:in `parse_nested_query'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/request.rb:375:in `parse_query'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/request.rb:213:in `POST'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/methodoverride.rb:26:in `method_override'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/methodoverride.rb:14:in `call'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
    App 17414 stderr:       from /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
    App 17414 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
    App 17414 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
    App 17414 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
    App 17414 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
    [Wed Jun 22 12:54:01.416608 2016] [core:error] [pid 10100:tid 140391311050496] [client 178.79.161.133:42795] End of script output before headers: harmonia

**Comment by floehopper** [comment]
I've worked around this issue by editing the body of the Harmonia task and replacing the only occurrence of "%" with "percent" and then re-assigning the task. A new [Trello card][1] has now successfully been created.

[1]: https://trello.com/c/FuCTnpTC

**Comment by floehopper** [comment]
I believe the original exception is connected to the discussion on [this Rack issue][1].

[1]: https://github.com/rack/rack/issues/337

**Comment by floehopper** [comment]
I've just reproduced this exception using a new action:

```ruby
  post '/percent' do
    json = request.body.read
    attributes = JSON.parse(json)
    [200, attributes.inspect]
  end
```

And sending the following POST request:

```
curl -X POST -d '{"percent": "%"}' http://localhost:9292/percent
# => ArgumentError: invalid %-encoding ({"percent": "%"})
```

I then noticed this related issue and discovered that setting a content-type header to JSON avoided the exception being raised:

```
curl -X POST -H 'Content-Type:application/json' -d '{"percent": "%"}' http://localhost:9292/percent
# => {"percent"=>"%"}
```

In fact it turns out that setting the content type to `application/x-www-form-urlencoded` or empty string also leads to the exception being raised:

```
curl -X POST -H 'Content-Type:application/x-www-form-urlencoded' -d '{"percent": "%"}' http://localhost:9292/percent
# => ArgumentError: invalid %-encoding ({"percent": "%"})
```

```
curl -X POST -H 'Content-Type:' -d '{"percent": "%"}' http://localhost:9292/percent
# => ArgumentError: invalid %-encoding ({"percent": "%"})
```

I think my conclusion is that Harmonia probably isn't setting a content-type header, but ought to be.

Having said that, I think we can reasonably assume that all requests to this app are currently expected to have a JSON content-type, so I'm going to investigate adding some custom middleware to inject this header as suggested in [this comment][1].

/cc @lazyatom 

[1]: https://github.com/sinatra/sinatra/issues/804#issuecomment-48103635

**Comment by floehopper** [comment]
Note that my fix is to *force* the content type of all incoming requests to be `application/json`. This isn't ideal and should be removed if Harmonia starts sending the correct header.

**Comment by floehopper** [comment]
I've been in touch with James and he's just deployed a fix which should set the Content-Type header correctly, so we could probably remove [my bodge][1].

[1]: https://github.com/freerange/webhooks/commit/1fb3674c1959503aa4f44f7864697e68b422c68c
