### ISSUE TITLE
Investigate intermittent Trello::Error exception

### ISSUE THREAD

**Issue by floehopper** [freerange/webhooks#22]
We've seen [this exception][1] happen 3 times in recent weeks. It would be good to investigate why it might be happening. If it's something out of our control it would be good to see whether we can be more robust to the problem e.g. by retrying...? I think the following is the server-side log for the 3rd of the exceptions (i.e. the one that happened earlier today):

```
App 22367 stderr: Trello::Error - Trello::Error:
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.2.1/lib/trello/client.rb:99:in `invoke_verb'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.2.1/lib/trello/client.rb:24:in `post'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.2.1/lib/trello/webhook.rb:68:in `save'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.2.1/lib/trello/basic_data.rb:28:in `save'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.2.1/lib/trello/client.rb:67:in `create'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/ruby-trello-1.2.1/lib/trello/webhook.rb:42:in `create'
App 22367 stderr:       /home/webhooks/app/app.rb:78:in `block in <class:WebhooksApp>'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/airbrake-4.1.0/lib/airbrake/rack.rb:46:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/logger.rb:15:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/commonlogger.rb:33:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/head.rb:11:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/rack-1.5.4/lib/rack/methodoverride.rb:21:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
App 22367 stderr:       /home/webhooks/app/vendor/gems/ruby/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
App 22367 stderr:       /home/webhooks/app/force_json_content_type_middleware.rb:8:in `call'
App 22367 stderr:       /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
App 22367 stderr:       /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 22367 stderr:       /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 22367 stderr:       /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
App 22367 stderr: 
App 22367 stderr: 178.79.161.133 - - [08/Aug/2016 08:49:00] "POST /harmonia/assignments?token=fReax2i1oj7aV4Ur " 500 30 11.5477
```

[1]: https://gofreerange-errbit.herokuapp.com/apps/542ae6297b273bee6c000050/problems/579743024513170006000000

**Comment by floehopper** [comment]
For the specific stack trace in this issue, the problem occurred when trying to create the Trello webhook for a newly created card. However, it seems as if this exception has happened in a few different places, basically it could happen in any of the places where a request is sent to the Trello API.

I've tried to see whether there's a way to get any more detail about the nature of the exception, but haven't had any luck.

One thing I wondered about is whether we might be running into the [Trello API rate limit][1]. This is probably more likely when there are a lot of cards in the To Do list, because the card sorting mechanism has to update the position of each card one at a time. This sorting happens after the creation of each card. So if multiple cards were created one after the other, it _might_ be quite a lot of requests. However, I've just tried hitting the rate limit from the console and haven't managed it, but perhaps that's because I'm running single-threaded and perhaps the server is effectively multi-threaded...?

[1]: http://help.trello.com/article/838-api-rate-limits
